### PR TITLE
Modified client api to create new methods on AccumuloClient for creating EC scanners

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by keith-turner** [comment]
I am not a big fan of this. If we are going to add something to the API we should endeavor to create the method we think should be in the API.  I think these methods do not set a good precedent (do we want a bunch of createXScanner() method hanging off AccumuloClient?) and do not follow the existing precedents of the Accumulo API.  In the existing API the Scanner is really is a factory for iterators where config is done before creating the iterator.  The setConsistencyLevel method on the scanner followed this existing precedent.  Following existing precedents and not introducing new ones without consideration of the evolutionary impacts will help make the API easier to understand. 

I do like the goal of this PR, but I am not sure of the best way to achieve it.  Well I am inferring a goal.  I am thinking the goals are the following.

  * Make it so that developers have to go out of their way to opt in to using experimental APIs.
  * Clearly mark experimental APIs and state they are evolving and subject to change.

I was thinking we could add an `@Experimental` annotation to the setConsistencyLevel method, however I don't think a strategy like that has worked well for Hadoop and Guava.  For Guava and Hadoop there is no widespread automation that prevents developers from using these methods in an opt-in manner, so you constantly end up using method you maybe should not when doing completion in your IDE.  To combat this every user of Accumulo would need build plugins that check for use of these experimental APIs, maybe that is ok if we document it.  This was something I was thinking of, but I Am really uncertain about.  Just posting if for discussion.

Another thing I thought of and I am also uncertain about is having a parallel experimental API.  For this, users would not ever accidentally stumble on using it.  They would have to opt in.  For the parallel API we would have experimental classes that extend the regular classes and exist in a package like `o.a.a.core.experimental`.  Using this would look like the following.

```java
  try(ExperimentalAccumuloClient eaClient = Accumulo.newClient().buildExperimental()) {
      ExperimentalScanner scanner = eaClient.newScanner();
      scanner.setConsistencyLevel(EVENTUAL);
      // do stuff w/ scanner
      // since ExperimentalScanner extends Scanner so it can be passed/assigned to code that takes a scanner
     Scanner regularScanner = scanner;
     // the following would not compile because Scanner does not have the method
    regularScanner.setConsistencyLevel(EVENTUAL);
 }
```

I like that this approach solves the accidental use of experimental APIs very cleanly, no one is going to use the above w/o explicitly opting in   However I am unsure if its a workable solution and if it is workable how much code does it add? I suspect it might work w/ a little code, but would only know for sure by trying.

**Comment by dlmarion** [comment]
The current contents of this PR was my interpretation of what was suggested to me. Talking with the person who made the suggestion, what you have below aligns more with what they meant. I believe the points were:

1. Documentation is insufficient as it may not be read (you mentioned this above)
2. That the experimental feature could easily be excised from the codebase is needed

```
try(ExperimentalAccumuloClient eaClient = Accumulo.newClient().buildExperimental()) {
```

My only concern with this approach is whether or not there needs to be two entirely separate code paths in the client. Creating a different client is going to be easier than creating a different client, scanner implementations, ThriftScanner's, etc. How far down the stack does this go?

**Comment by keith-turner** [comment]
> My only concern with this approach is whether or not there needs to be two entirely separate code paths in the client. Creating a different client is going to be easier than creating a different client, scanner implementations, ThriftScanner's, etc. How far down the stack does this go?

My hope is that it could be superficial at the API level.  That in the impl level things are just ExperimentalScanner, ExperimentalAccumuloClient, etc types , but the Scanner type does not have the experimental methods.  So hopefully we could have a single impl with this approach and just cleanly delineate experimental using types in the API w/o much fuss in the impl.  But not sure if this is possible.

**Comment by dlmarion** [comment]
So, I'm good with closing this PR and letting the person who made the suggestion make their case on the new ScanServers PR.

**Pull request closed without merging**
